Migrate multiple tests from Boost to Catch2
mlpack/mlpack pull request #2677
Opened 2020-10-18 11:30 UTC by Aakash-kaushik

List of migrated tests: 
- drusilla_select_test.cpp
- emst_test.cpp
- fastmks_test.cpp
- facilities_test.cpp
- hpt_test.cpp
- hyperplane_test.cpp
- init_rules_test.cpp
- kde_test.cpp
- linear_svm_test.cpp
- main_tests/emst_test.cpp
- main_tests/fastmks_test.cpp
- main_tests/kde_test.cpp
- main_tests/linear_svm_test.cpp

2020-10-18 19:56 UTC, jeffin143 requested changes
Took a pass , there are many instances were 
Close when migrated should have the value / 100
Please change it at every location

I was reviewing it through mobile :) so pointed out some of those

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/drusilla_select_test.cpp
> +    REQUIRE(distances[i] == Approx(distancesTrue[i]).epsilon(1e-5));
```suggestion
    REQUIRE(distances[i] == Approx(distancesTrue[i]).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/drusilla_select_test.cpp
> +    REQUIRE(distances[i] == Approx(distancesXml[i]).epsilon(1e-5));
```suggestion
    REQUIRE(distances[i] == Approx(distancesXml[i]).epsilon(1e-7));
```

Same for others too

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 0) == Approx(0.08).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 0) == Approx(0.08).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 1) == Approx(0.09).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 1) == Approx(0.09).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 2) == Approx(0.1).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 2) == Approx(0.1).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 3) == Approx(0.22).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 3) == Approx(0.22).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 4) == Approx(0.25).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 4) == Approx(0.25).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 5) == Approx(0.27).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 5) == Approx(0.27).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 6) == Approx(0.46).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 6) == Approx(0.46).epsilon(1e-7));
```

2020-10-18 19:56 UTC, jeffin143 commented on src/mlpack/tests/emst_test.cpp
> +  REQUIRE(results(2, 7) == Approx(0.7).epsilon(1e-5));
```suggestion
  REQUIRE(results(2, 7) == Approx(0.7).epsilon(1e-7));
```

2020-10-18 20:31 UTC, Aakash-kaushik commented
> Took a pass , there are many instances were 
> Close when migrated should have the value / 100
> Please change it at every location
> 
> I was reviewing it through mobile :) so pointed out some of those

Hey @jeffin143 will make changes to all the files in morning. 🌅

2020-10-19 06:36 UTC, Aakash-kaushik commented
> Took a pass , there are many instances were
> Close when migrated should have the value / 100
> Please change it at every location
> 
> I was reviewing it through mobile :) so pointed out some of those

Got everyone :D

2020-10-19 08:01 UTC, Aakash-kaushik commented
```
/home/vsts/work/1/s/src/mlpack/tests/linear_svm_test.cpp:849: FAILED:
  REQUIRE( testAcc == Approx(1.0).epsilon(0.0035) )
with expansion:
  0.996 == Approx( 1.0 )
```
I have increase the tolerance value to 0.0045, because if left 0.0035 it sometimes passes and sometimes does not and will be a hassle in all future PRs.

2020-10-20 10:04 UTC, Aakash-kaushik commented
closing in favor of #2678

2020-10-20 10:04 UTC, closed without merging