Bump minimum Armadillo version to 9.800.6
mlpack/mlpack pull request #3043
Opened 2021-08-29 00:25 UTC by zoq

Bump minimum Armadillo version to 9.800.6, see https://github.com/mlpack/ensmallen/pull/318 for more details.

2021-08-29 12:46 UTC, shrit approved these changes
I am wondering if we merge this, would it resolve the issue presented in #2953

2021-08-30 14:01 UTC, conradsnicta requested changes

2021-08-30 14:35 UTC, rcurtin approved these changes
Looks good to me once Conrad's comments are handled. Once this is merged, I'll update the CI build matrix to only use Armadillo 9.800 or newer. :+1:

2021-08-31 05:01 UTC, conradsnicta approved these changes

2021-08-31 13:41 UTC, merged