Implementation - Padé Approximant in Log Softmax Layer
mlpack/mlpack pull request #3685
Opened 2024-04-10 13:55 UTC by MarkFischinger

Following our discussion in issue #3662, I've implemented the pade approximant in the log softmax layer. Due to time constraints, I haven't run the tests yet, but I plan to do so shortly and update you with the results.

2024-04-10 20:51 UTC, shrit reviewed
Would you use mlpack style for variables ?

2024-04-10 21:49 UTC, MarkFischinger commented
@shrit, thank you for pointing that out. The new commit includes the fix :)

2024-04-11 10:36 UTC, shrit approved these changes

2024-04-11 10:38 UTC, shrit commented
I approved this one too quickly, I did not see the that the tests were not passing. 
@MarkFischinger could you try to run the tests locally ? 
I would be nice to compare the matrices generated by the original fast method and Padé because I think there are a good amount of difference, otherwise the tests would not have failed ?

2024-04-11 13:01 UTC, rcurtin requested changes
Just preventing mlpack-bot from auto-approving until we get the fixes worked out.  I'm guessing that the level of approximation might be too high, and things are not converging?  (Maybe a threshold like `x < 13` is needed?)

2024-04-11 13:01 UTC, rcurtin commented on src/mlpack/methods/ann/layer/log_softmax_impl.hpp
> +    return padeApproximant(x);
I think it would be a bit cleaner to just inline the whole approximant into the lambda, but, up to you.

2024-04-12 23:27 UTC, MarkFischinger commented
@shrit @rcurtin Sorry for the delay with the benchmarks -I needed to run a more detailed analysis to find an effective solution.
Here’s what I found:

Mnist Simple
**Old Implementation:**
_Validation Loss: 567.577
Duration: 79709ms
Loss: 0.0331713
Accuracy: Train = 98.463%, Valid = 97.0707%_

**New Implementation (Scale 4, x < 13.0):**
_Validation Loss: 563.98
Duration: 80412ms
Loss: 0.049433
Accuracy: Train = 98.3571%, Valid = 96.9517%_

The initial idea of adding only `x < 13.0` proved too broad, leading to uncontrolled error spikes due to the large $X$ values I had been concerned about. In the discussion issue example, it featured only small X values, which worked perfectly with the Padé approximation, but large  values (above 8.0) do not work quite well. But by scaling $X$ by $4$, I reduced the error, now notably smaller than in the old version, as you can see in this graph: 

![errors_and_time_4_4_fair](https://github.com/mlpack/mlpack/assets/64029109/1a996385-3650-463f-be6e-cce8bf4aaffd)

Despite the graph showing a seemingly doubled duration in runtime, the actual difference in the cnn run is minor. This improvement could be a viable option for implementation? What do you think?

```cpp
auto scaledPadeApproxExpMinusX = [](double x) {
    if (x < 13.0) {
      double s = 4.0;
  
      double xs = x / s;
  
      double numerator = 24 - 12*xs + 4*xs*xs - xs*xs*xs;
      double denominator = 24 + 12*xs + 4*xs*xs + xs*xs*xs;
  
      double pade = numerator / denominator;
      return std::pow(pade, s);
    }
  
    return 0.0;
  };

  output.transform([scaledPadeApproxExpMinusX](double x) {
    return scaledPadeApproxExpMinusX(x);
  });
```
I think I will also test the algorithm on mnist_cnn soon.

2024-04-16 11:16 UTC, shrit commented
@MarkFischinger give it a try, what I find weird is that, when we tested this separately the time was way faster, while here it looks much slower than the original one.
This worth investigating.

2024-04-16 15:05 UTC, MarkFischinger commented
Hey @shrit, I think the trouble we're seeing comes from the higher $X$ values in our MNIST examples. Originally, we only saw $X$ values above $4$ about $2.275$% of the time, based on our normal distribution setup with `arma::mat output = arma::randn(1000, 1000, arma::distr_param(0, 2))`. But the MNIST data showed much higher $X$ values frequently, which caused those spikes and ultimately broke the code. That's why I had to scale them down, which did slow our runtime a bit.

Here are the $X$ values for the mnist example (output):
```
x = 8.78431
x = 23.1975
x = 22.0821
x = 16.2784
x = 18.5682
```

I'm thinking, since lower $X$ values are more common and they handle better, maybe we should try the original Padé approximation for values up to say, $4$, and keep our current method as a backup for anything higher. This way, we can handle typical cases fast and still catch any outliers without any problems. What do you think? Should I run some benchmarks on this mixed approach?

2024-04-16 21:47 UTC, rcurtin commented
Yeah, a switch to the existing implementation at about `x > 4` would probably do the trick for convergence too.  I would be interested to see if it would be faster, too---although, to check that, you'd need to ensure that the number of epochs used for training are constant (or, just time a single epoch, that's fine too).

The scaling trick is definitely a good one for convergence, but I suspect the `std::pow` is painful and what causes it to be slower.

2024-04-22 22:36 UTC, MarkFischinger commented
@rcurtin I did some backtesting, and the results showed unfortunately no/only minor improvements in runtime. Statistically, combining those two algorithms should reduce the error, but I'm still looking for faster implementations because I'm hopeful that I can find a better solution. I'll update you as soon as possible, though my available time will be limited for the next few days due to the exams :/

2024-05-06 20:08 UTC, rcurtin commented
I also wonder if it would be possible to get additional speedup by writing a loop that the compiler can autovectorize. I doubt that `.transform()` on arbitrary lambda functions could make use of it. In Armadillo this is often done with a for loop that computes values for 2 or 4 items at once, and is written such that each operation for each element has no data dependency on previous iterations of the loop.  I can probably find an example if you like, just let me know if you want to try that out. :+1:

2024-06-24 12:02 UTC, MarkFischinger commented
@shrit @rcurtin I'm adding targeted OpenMP parallelization to the Padé approximant computation. I’ve applied parallel processing to improve the performance of this approximant without the fast approximation function, which doesn’t gain from parallel execution here.

Here are the benchmarks of the commits: 
![grafik](https://github.com/mlpack/mlpack/assets/64029109/e201d62f-4af9-46bf-b143-aa0a462503f9)

 They have an almost identical error, so that should not be an error. 
![grafik](https://github.com/mlpack/mlpack/assets/64029109/3a3d6f9a-69a6-4ed8-9962-e555c48faca7)

I'm also working/testing one more optimization :)

2024-06-24 12:17 UTC, rcurtin commented
Nice, the numbers look good. :+1: Two quick checks:

 * Does the `mnist_cnn` example still converge to the same accuracy?  That is just a quick sanity check to ensure that the changed error rates are not a problem.

 * Was the original implementation OpenMP-ized? If not, it could be worth a quick test to add OpenMP there too, just to make sure that the speedup you are seeing is not entirely just due to OpenMP.

2024-06-25 15:15 UTC, MarkFischinger commented
@rcurtin You're right, the default fast approx with OpenMP is quicker. I've gone ahead and committed the OpenMP-ized fast approx version :)

2024-06-25 15:27 UTC, rcurtin reviewed
It's unfortunate the Pade approximant didn't work out, but sometimes that's how it goes---I definitely know the feeling of spending many weeks investigating something only to find at the end of the day that the clever idea didn't work out.  Do you think you want to call it case closed on the Pade approximant, or do you still have some ideas or thoughts that might help out?

As a side note, I personally would focus not on microbenchmarks (although they are definitely useful!) but instead on the actual real-world measured time for training in e.g. the `mnist_cnn` example.  Personally I will use microbenchmarks to try and guide my development, but the "ground truth" I use to decide whether or not anything really is faster is an actual fully-working example, since this is closer to what a user will see in practice. :+1:

2024-06-25 15:34 UTC, rcurtin commented
Also it would be great if you could provide some updated numbers on how much OpenMP helps, etc., just to give an idea---I haven't run the updated code myself, but I'm sure that you have in your experiments. :+1:

2024-06-26 12:31 UTC, MarkFischinger commented
@rcurtin I'll return to this if I get another idea, but the current commit should be merged, because the openMP fast approximation shows a noticeable speed boost. Here are the MNIST dataset benchmarks :)

Fast Approximation without OpenMP 
```
756/756 [====================================================================================================] 100% - 79.897s/epoch; 105ms/step; loss: 9.42397

Validation loss: 10191.9.
Time elapsed: 82497ms
Accuracy: train = 70.4048%,      valid = 70.1429%
```



**Fast Approximation with OpenMP**

```
756/756 [====================================================================================================] 100% - 73.3507s/epoch; 97ms/step; loss: 9.42397
Validation loss: 10191.9.
Time elapsed: 75912ms
Accuracy: train = 70.4048%,      valid = 70.1429%
```

Padé approximant with OpenMP
```
756/756 [====================================================================================================] 100% - 74.6628s/epoch; 98ms/step; loss: 19.4617
Validation loss: 76287.9.
Time elapsed: 77906ms
```

2024-06-26 21:45 UTC, rcurtin approved these changes
@MarkFischinger nice work, great to see we did end up getting an improvement here (even if it's not the one you were originally looking for :)).

Do you want to add a small bullet point to `HISTORY.md` indicating the speedup?

@conradsnicta just an FYI: we got some speedup in this PR over using `.transform()` and `.each_col()`, but the primary method of speedup is via OpenMP parallelization.  I notice that neither `.transform()` nor `.each_col()` are OpenMP-ized---wanted to call it to your attention in case you wanted to incorporate that into the next Armadillo release.

2024-06-27 12:04 UTC, shrit approved these changes
Eventually, we started with Padé and ended up with the original implementation parallelized and removed the transform function

2024-07-03 16:24 UTC, merged