Document `AMF`
mlpack/mlpack pull request #3729
Opened 2024-06-07 00:00 UTC by rcurtin

This PR documents the generic `AMF` class.  I think this is my first major attempt to document such a generic class; AMF itself doesn't have a binding or anything, as it is meant to be used with its template parameters to provide a generic algorithm.

Here is compiled documentation:

http://ratml.org/misc/mlpack-markdown-doc/user/methods/amf.html

There were a number of code changes that were necessary.  The primary changes were to adapt all update rules for `AMF` to accept arbitrary `MatType`s and add tests for them.  This required a fair amount of refactoring of `SVDBatchLearning`, `SVDIncompleteIncrementalLearning`, and `SVDCompleteIncrementalLearning`, since those had effectively completely different implementations depending on whether the matrix was sparse or dense.  The functionality is the same.

There were a couple other changes throughout:

 * Fix convenience typedefs for names like `SVDIncompleteIncrementalFactorizer` to use the appropriate termination policies.
 * The `RandomAcolInitialization` class did not have the `InitializeOne` member that is required for `MergeInitialization`, so I added it.
 * Fix link to "Making k-means even faster", which kept failing in the documentation jobs.  I figured changing the URL was easiest here.
 * Fix a couple minor errors I found in the NMF documentation.

2024-06-08 12:03 UTC, shrit approved these changes
Everything looks good to me

2024-06-09 15:40 UTC, shrit requested changes
just a place holder so we do not merge by accident due to test failure

2024-06-10 10:14 UTC, shrit approved these changes

2024-06-11 12:08 UTC, rcurtin commented
Ok!  Got all the little documentation build issues worked out too.  Hopefully that job will continue to get more robust.

2024-06-11 12:08 UTC, merged