Optimized the backward convolution function
mlpack/mlpack pull request #3738
Opened 2024-06-12 20:02 UTC by MarkFischinger

I've made several optimizations to the backward function in the convolution code; the main areas of improvement include padding, rotation, and dilation operations. These changes aim to reduce computational overhead and a speed up.

**Changes**

_Padding Optimization_
Instead of adding padding to the input data separately, I've integrated the fixed padding values directly into the convolution operation. This reduces the number of steps required.

_Rotation Optimization_
The previous method involved rotating filters by 180 degrees. To optimize this, I replaced the rotation with a combination of matrix flipping or transposing followed by reversing. Additionally I embedded the rotation directly into the convolution step, which simplifies the overall computation.

_Dilation Optimization_
For consistent and predetermined dilation factors, I've embedded these directly into the convolution. This minimizes the total computational workload and enhances performance.

I'm happy to show you these benchmarks run based on the mnist-code from the [mlpack-benchmarks repo](https://github.com/MarkFischinger/mlpack-benchmarks/blob/master/src/convolutional/backward/mnist/mnist_benchmark.cpp):
```
Time Elapsed: 73222ms (original)
Time Elapsed: 50517ms (optimized)
```

2024-06-13 09:13 UTC, shrit requested changes
The `GradientConvolutionLayerWithStrideTest` is failing, is this happening as well on your machine? I did not run this locally, could you look into this one ?

2024-06-13 09:13 UTC, shrit commented on src/mlpack/methods/ann/layer/convolution_impl.hpp
> +  const bool usingPadding = (padWLeft != 0 || padWRight != 0 || padHTop != 0 || padHBottom != 0);
please keep the line under 80 characters, basically identical to how it was

2024-06-13 09:13 UTC, shrit commented on src/mlpack/methods/ann/layer/convolution_impl.hpp
> +                              mappedError.n_slices);
The same for this one, please keep it under 80 chars

2024-06-16 18:38 UTC, MarkFischinger commented
@shrit After a lot testing/debugging, I believe I have finally found the issue. This should resolve it.

2024-06-18 17:42 UTC, MarkFischinger commented on src/mlpack/methods/ann/layer/convolution_impl.hpp
> +          }
Updated my IDE configuration. This shouldn't happen again :)

2024-06-27 22:05 UTC, MarkFischinger commented
So, I found out that these small adjustments increased the speed by approximately 30.5%.

Here are the MNIST benchmarks:
**Original**
```
756/756 [====================================================================================================] 100% - 59.914s/epoch; 79ms/step; loss: 9.42397
Validation loss: 10191.9.
Time elapsed: 61458ms
Accuracy: train = 70.4048%,      valid = 70.1429%
```


**Optimized**
```
756/756 [====================================================================================================] 100% - 41.1419s/epoch; 54ms/step; loss: 9.42397
Validation loss: 10191.9.
Time elapsed: 42741ms
Accuracy: train = 70.4048%,      valid = 70.1429%
```

2024-06-28 15:06 UTC, rcurtin approved these changes
Looks good!  The speedup is nice.

2024-06-28 15:07 UTC, zoq approved these changes

2024-07-06 21:27 UTC, shrit approved these changes

2024-07-06 21:28 UTC, merged