Loss functions XGB
mlpack/mlpack pull request #3749
Opened 2024-06-26 20:33 UTC by TirelessClock

Started working on new loss functions more specific to XGB.
Continuing from PR #3747

2024-06-26 22:23 UTC, rcurtin commented on src/mlpack/methods/decision_tree/log_loss.hpp
> +#include <cmath>
Trivial comment but I think that this is already included by `prereqs.hpp` or `base.hpp`. :+1:

2024-07-01 10:42 UTC, shrit requested changes
@TirelessClock could you add a couple of tests for this loss function ?

2024-07-01 10:42 UTC, shrit commented on src/mlpack/methods/decision_tree/log_loss.hpp
> +
```suggestion
```

2024-07-01 10:42 UTC, shrit commented on src/mlpack/methods/decision_tree/log_loss.hpp
> +
```suggestion
```

2024-07-01 10:42 UTC, shrit commented on src/mlpack/methods/decision_tree/log_loss.hpp
> +
```suggestion
```

2024-07-01 10:42 UTC, shrit commented on src/mlpack/methods/decision_tree/log_loss.hpp
> +
```suggestion
```

2024-07-16 09:15 UTC, closed without merging