Added Installation Guide for macOS ARM Silicon Machines in README
mlpack/mlpack pull request #3773
Opened 2024-07-24 14:22 UTC by Jayaprakash0511

This pull request adds a detailed installation guide for users who want to install and run mlpack on macOS ARM Silicon machines. The guide covers the following steps:
        1.	Install Homebrew:
	•	Provides the Homebrew installation command and instructions to add Homebrew to the PATH.
	2.	Install Dependencies:
	•	Steps to install armadillo and mlpack using Homebrew.
	3.	Verify Installation:
	•	Instructions to check if mlpack and armadillo include and lib files are symlinked correctly in /opt/homebrew.
	4.	Explanation of Dependencies:
	•	Detailed explanation of how mlpack depends on armadillo for linear algebra tasks and how armadillo uses OpenBLAS and LAPACK provided by macOS’s Accelerate framework.
	5.	Compile Command Example:
	•	Provides a compile command example to show how to compile a sample mlpack code with the necessary flags and framework links.

Changes:

	•	Added a new section in the README file under “Installation on macOS ARM Silicon Machines”.
	•	Included detailed steps with commands and explanations to guide users through the installation process.
	•	Provided a compile command example to demonstrate how to compile mlpack code with the Accelerate framework.

By including this detailed installation guide, we hope to make it easier for users to set up and use mlpack on their macOS ARM Silicon machines without encountering common installation, linking and compiling issues.

2024-07-24 16:14 UTC, rcurtin requested changes
Thanks for the contribution.  But it is really important to keep documentation concise.  We can expect that users who know what Homebrew is can figure out how to install it themselves.  I would rather we just add a note to the C++ quickstart (which is the more appropriate place anyway) mentioning under the Fedora/RHEL install command that mlpack can also be installed through Homebrew (and nothing else).

2024-07-24 16:43 UTC, Jayaprakash0511 commented
> Thanks for the contribution. But it is really important to keep documentation concise. We can expect that users who know what Homebrew is can figure out how to install it themselves. I would rather we just add a note to the C++ quickstart (which is the more appropriate place anyway) mentioning under the Fedora/RHEL install command that mlpack can also be installed through Homebrew (and nothing else).

Thank you for the feedback. I understand the importance of keeping the documentation concise and appreciate the need to guide users effectively. My main intention with the detailed installation guide was to address the common issues users face when installing mlpack on macOS ARM silicon machines, particularly around OpenBLAS and LAPACK dependencies.

Many users have encountered errors due to improper handling of these dependencies. The -DARMA_DONT_USE_WRAPPER and -framework Accelerate, both flags are crucial for resolving these issues, and without them, users might struggle to get mlpack working correctly.

2024-07-25 05:47 UTC, conradsnicta commented
@Jayaprakash0511 It's not clear why `-DARMA_DONT_USE_WRAPPER` is required.  The Armadillo runtime library already links with the Accelerate framework under macOS.

2024-07-25 06:12 UTC, Jayaprakash0511 commented
> @Jayaprakash0511 It's not clear why `-DARMA_DONT_USE_WRAPPER` is required. The Armadillo runtime library (the wrapper library) already links with the Accelerate framework under macOS.

That's where the problem is. Without `-DARMA_DONT_USE_WRAPPER`, some kind of wrapper issues are occurring. 
<img width="1421" alt="Screenshot 2024-07-25 at 11 39 55 AM" src="https://github.com/user-attachments/assets/c7d7fb8b-6d7c-4793-bc91-bc3fdec7eb71">

2024-07-25 07:05 UTC, conradsnicta commented
@Jayaprakash0511 The error stems from not linking with the Armadillo runtime library. In other words, link with `-larmadillo`.  Example:
```
g++ code.cpp -o code -O2 -larmadillo
```
(add `-I` and `-L` as required for your setup)
 
The linking is explained in Armadillo's README.md and FAQ:
* https://gitlab.com/conradsnicta/armadillo-code
* https://arma.sourceforge.net/faq.html

2024-07-25 07:14 UTC, Jayaprakash0511 commented
> @Jayaprakash0511 The error stems from not linking with the Armadillo runtime library. In other words, link with `-larmadillo`. Example:
> 
> ```
> g++ code.cpp -o code -O2 -larmadillo
> ```
> 
> (add `-I` and `-L` as required for your setup)
> 
> The linking is explained in Armadillo's README.md and FAQ:
> 
> * https://gitlab.com/conradsnicta/armadillo-code
> * https://arma.sourceforge.net/faq.html

Oh, got it!! Thank you for the response.!

2024-07-26 04:11 UTC, closed without merging