Release version 4.4.1
mlpack/mlpack pull request #3797
Opened 2024-09-16 13:18 UTC by rcurtin

This automatically-generated pull request adds the commits necessary to make the 4.4.1 release.

Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so that it doesn't include the new HISTORY block) and publish it.

When you merge this PR, be sure to merge it using a *rebase*.

### Changelog

 * Distribute STB headers as part of R package (#3724, #3726).

 * Added OpenMP parallelization to Hamerly, Naive, and Elkan k-means (#3761, #3762, #3764).
 
 * Added OpenMP support for fast approximation (#3685).

 * Implemented the Find and Fill algorithm into the Dropout Layer and added OpenMP support (#3684).

 * Update Python bindings to support NumPy 2.x (#3752).

 * Bump minimum Armadillo version to 10.8 (#3760).

 * Adapt `NearestInterpolation` ANN layer to new Layer Inteface (#3768).

 * Add support for arbitrary matrix types to `Radical` and deprecate `Radical::DoRadical()` in favor of `Radical::Apply()` (#3787).

2024-09-16 13:21 UTC, shrit approved these changes

2024-09-16 15:17 UTC, conradsnicta commented
@rcurtin Suggest to call this release 4.5.0 rather than 4.4.1.

Bumping the patch level (the last .1) usually indicates bug fixes, with no additions or other improvements.  This is definitely not the case here.

Instead, it's a decent minor release, and calling it 4.4.1 undersells the improvements and changes.  It deserves to be called 4.5.0.

People like shiny things and bigger numbers, so from a marketing perspective it'd be useful to send the right message.

2024-09-17 01:46 UTC, conradsnicta commented on HISTORY.md
> +## mlpack 4.4.1
suggest to bump the version to 4.5.0, as per my earlier comment

2024-09-17 01:47 UTC, conradsnicta requested changes
suggest to bump the version to 4.5.0, as per my earlier comment

2024-09-17 13:09 UTC, rcurtin commented
Fair enough, opened #3798 to bump to 4.5.0 instead.

2024-09-17 13:09 UTC, closed without merging