Release version 4.5.1
mlpack/mlpack pull request #3844
Opened 2024-12-03 00:32 UTC by rcurtin

This automatically-generated pull request adds the commits necessary to make the 4.5.1 release.

Once the PR is merged, mlpack-bot will tag the release as HEAD~1 (so that it doesn't include the new HISTORY block) and publish it.

When you merge this PR, be sure to merge it using a *rebase*.

### Changelog

 * Fix compilation with clang 19 (#3799).

 * Deprecate version of `data::Split()` that returns a `std::tuple` for consistency; use other overloads instead (#3803).

 * Fix LSTM layer copy/move constructors (#3809).

 * Fix compilation if only including `mlpack/methods/kde/kde_model.hpp` (#3800).

 * Fix serialization and `MinDistance()` bugs with `HollowBallBound` (#3808).

2024-12-03 01:55 UTC, eddelbuettel requested changes

2024-12-03 01:55 UTC, eddelbuettel commented on src/mlpack/core/util/version.hpp
> +#define MLPACK_VERSION_PATCH 2
Why are we setting it to 2 here when it is supposedly 4.5.1 ?

2024-12-03 02:36 UTC, eddelbuettel commented on src/mlpack/core/util/version.hpp
> +#define MLPACK_VERSION_PATCH 2
Gotcha. I was about to add 'or maybe I do not understand the local process well enough' so it is HEAD~1 for the release and this is one ahead. (I tend to split those. Oh well.)

"Not obvious, though." as the kids say.  Thanks for the clue bat wave.

2024-12-03 02:36 UTC, eddelbuettel approved these changes
All good

2024-12-04 18:05 UTC, shrit approved these changes

2024-12-04 19:03 UTC, merged